In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
train_data=pd.read_csv('data1.csv')
validate_data=pd.read_csv('data2.csv')

In [4]:
train_data2=pd.read_csv('data3.csv')
train_x=pd.concat([train_data, train_data2])
train_x.head()

0         1         2         3         4         5         6  \
0 -0.320710 -0.813104 -1.797856 -2.671061 -3.103414 -2.988188 -2.511264   
1  0.961586  0.989782  0.835355  0.574514  0.386786  0.447138  0.832640   
2  0.949166  0.805315  0.293494 -0.344036 -0.910021 -1.272160 -1.433150   
3  0.413452  0.046589 -0.298862 -0.571118 -0.839083 -1.210393 -1.674694   
4  0.661680  0.707341  0.453906  0.018676 -0.496279 -1.036679 -1.624540   

          7         8         9    ...          590       591       592  \
0 -1.782173 -0.957324 -0.046539    ...    -1.335625 -1.465457 -1.202740   
1  1.519390  2.371436  3.087012    ...    -0.656175 -0.949323 -1.478014   
2 -1.559474 -1.808059 -2.157373    ...     0.507871  0.489067  0.748604   
3 -2.039657 -2.092754 -1.834460    ...    -0.869120 -0.388985  0.131208   
4 -2.279095 -2.804397 -2.860567    ...    -1.782014 -1.935646 -2.017038   

        593       594       595       596       597       598       599  
0 -0.706720 -0.313735 -0.341366 -0.912081 -1.889642 -2.927776 -3.624055  
1 -2.073809 -2.520703 -2.747426 -2.871896 -3.083014 -3.378452 -3.450052  
2  1.102645  1.308947  1.210047  0.823331  0.280396 -0.199167 -0.320009  
3  0.473263  0.459038  0.108430 -0.377032 -0.785222 -0.992103 -0.926204  
4 -2.030505 -2.001926 -1.968619 -1.952229 -1.972033 -2.073820 -2.284887  

[5 rows x 600 columns]

In [5]:
validate_data.shape

(48, 600)

In [6]:
y_train=pd.read_csv('labels.csv', header=None)
y_train=y_train.transpose()
train_y=pd.concat([y_train,y_train])

In [7]:
train_y.shape

(96, 1)

In [8]:
y_validate=y_train
y_validate.shape

(48, 1)

In [11]:
from sklearn.svm import SVC
model=SVC(kernel='linear',decision_function_shape='ovo',C=1)
model.fit(train_x,train_y)
pred_svc=model.predict(validate_data)

/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [13]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_validate, pred_svc)

array([[5, 2, 0, 5],
       [1, 6, 1, 4],
       [6, 1, 2, 3],
       [8, 0, 0, 4]])

In [15]:
from sklearn.metrics import classification_report
print(classification_report(y_validate,pred_svc))

              precision    recall  f1-score   support

           0       0.25      0.42      0.31        12
           1       0.67      0.50      0.57        12
           2       0.67      0.17      0.27        12
           3       0.25      0.33      0.29        12

    accuracy                           0.35        48
   macro avg       0.46      0.35      0.36        48
weighted avg       0.46      0.35      0.36        48



# Initial Conclusion

It seems the deep network performed much better than SVC. I haven't done parameter tuning I just used the other parameters whichgave us 100% accuracy last time

In [16]:
from sklearn.svm import SVC
model=SVC(kernel='poly',decision_function_shape='ovo',C=1, degree=4)
model.fit(train_x,train_y)
pred_svc=model.predict(validate_data)

/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.5/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [17]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_validate, pred_svc)

array([[ 9,  3,  0,  0],
       [ 0, 12,  0,  0],
       [ 0,  1, 11,  0],
       [ 0,  2,  0, 10]])

In [18]:
from sklearn.metrics import classification_report
print(classification_report(y_validate,pred_svc))

              precision    recall  f1-score   support

           0       1.00      0.75      0.86        12
           1       0.67      1.00      0.80        12
           2       1.00      0.92      0.96        12
           3       1.00      0.83      0.91        12

    accuracy                           0.88        48
   macro avg       0.92      0.88      0.88        48
weighted avg       0.92      0.88      0.88        48



# Second Conclusion
Surprise Surprise using poly fit with degree 4 increased the accuracy to more than 85%. Let's dig some more

In [19]:
from sklearn.svm import SVC
model=SVC(kernel='poly',decision_function_shape='ovo',C=1, degree=6)
model.fit(train_x,train_y)
pred_svc=model.predict(validate_data)

/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.5/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [20]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_validate, pred_svc)

array([[ 9,  3,  0,  0],
       [ 0, 12,  0,  0],
       [ 0,  4,  8,  0],
       [ 0,  4,  0,  8]])

In [21]:
from sklearn.metrics import classification_report
print(classification_report(y_validate,pred_svc))

              precision    recall  f1-score   support

           0       1.00      0.75      0.86        12
           1       0.52      1.00      0.69        12
           2       1.00      0.67      0.80        12
           3       1.00      0.67      0.80        12

    accuracy                           0.77        48
   macro avg       0.88      0.77      0.79        48
weighted avg       0.88      0.77      0.79        48



# Third Conclusion
Increasing the degree decreases the accuracy so poly has its limit at 5 I guess

In [22]:
from sklearn.svm import SVC
model=SVC(kernel='poly',decision_function_shape='ovo',C=1, degree=5)
model.fit(train_x,train_y)
pred_svc=model.predict(validate_data)

/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.5/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [23]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_validate, pred_svc)

array([[ 9,  3,  0,  0],
       [ 0, 12,  0,  0],
       [ 0,  3,  9,  0],
       [ 0,  2,  0, 10]])

In [24]:
from sklearn.metrics import classification_report
print(classification_report(y_validate,pred_svc))

              precision    recall  f1-score   support

           0       1.00      0.75      0.86        12
           1       0.60      1.00      0.75        12
           2       1.00      0.75      0.86        12
           3       1.00      0.83      0.91        12

    accuracy                           0.83        48
   macro avg       0.90      0.83      0.84        48
weighted avg       0.90      0.83      0.84        48



Yup, degree 4 yields the best result let's use rbf and see what we get

In [27]:
from sklearn.svm import SVC
model=SVC(kernel='rbf',decision_function_shape='ovo',C=1)
model.fit(train_x,train_y)
pred_svc=model.predict(validate_data)

/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.5/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [28]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_validate, pred_svc)

array([[12,  0,  0,  0],
       [ 2, 10,  0,  0],
       [ 0,  0, 12,  0],
       [ 2,  0,  0, 10]])

In [29]:
from sklearn.metrics import classification_report
print(classification_report(y_validate,pred_svc))

              precision    recall  f1-score   support

           0       0.75      1.00      0.86        12
           1       1.00      0.83      0.91        12
           2       1.00      1.00      1.00        12
           3       1.00      0.83      0.91        12

    accuracy                           0.92        48
   macro avg       0.94      0.92      0.92        48
weighted avg       0.94      0.92      0.92        48



# Final SVC Conclusion
Well this is the maximum accuraccy I can squeeze out using SVC which is above 90% and I think it is much better than deep neural network because-
1. The complexity of the whole system is reduced
2. The code is much simpler and efficient compared to a deep network
3. Much faster, much accracy!